### ISSUE TITLE
Huge spam when some features are disabled in the config.

### ISSUE THREAD

**Issue by RDKRACZ** [kwpugh/MoreGems#16]
I set
```
"extraToolsEnable": false,
"bowsEnable": false,
```
https://gist.github.com/RDKRACZ/95485c9290222f16223dccbb01922857

**Comment by kwpugh** [comment]
Yep, because Minecraft still reads all model and recipe JSON, and spits an error if the item/block is not registered.   General the reason why I don't like to disable item/blocks via the config, but I relented to requests.   If you know how to avoid that, let me know.

The messages are harmless since it is just a parsing error, although the spam at start might be annoying.

**Comment by RDKRACZ** [comment]
K

**Comment by RDKRACZ** [comment]
I will try some other mods that have an option to disable features. Maybe instead of disabling your items just make them uncraftable in some way and delete them from loot?
